image: lerk/corretto-8-ant-maven

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo ${env.MAVEN_REPO_USER}
    - exit 1
    - cp bluej/build.properties.template bluej/build.properties
    - sed -i -e "s,<JAVA_HOME>,`echo $JAVA_HOME`,g" bluej/build.properties
    - ant -lib greenfoot/lib/ -buildfile greenfoot/build.xml copy-imagelib
    - ant -lib bluej/lib/ -buildfile bluej/build.xml jar-core
    - ant -lib greenfoot/lib/ -buildfile greenfoot/build.xml dist
  artifacts:
    paths:
      - bluej/lib/bluejcore.jar
      - greenfoot/package/Greenfoot-core-3.0.jar

deploy:
  stage: deploy
  dependencies:
    - build
  before_script: []
  script:
    - mvn -s .m2/settings.xml --batch-mode -Dmaven.repo.local=.m2/repository deploy:deploy-file -Durl=https://nexus.gammel.cloud/repository/maven-releases/ -DrepositoryId=gammel -Dfile=bluej/lib/bluejcore.jar -DgroupId=org.bluej -DartifactId=bluej-core -Dversion=greenfoot-$(cat .version) -Dpackaging=jar -DgeneratePom=true -DgeneratePom.description="BlueJ Core."
    - mvn -s .m2/settings.xml --batch-mode -Dmaven.repo.local=.m2/repository deploy:deploy-file -Durl=https://nexus.gammel.cloud/repository/maven-releases/ -DrepositoryId=gammel -Dfile=greenfoot/package/Greenfoot-core-3.0.jar -DgroupId=org.greenfoot -DartifactId=greenfoot -Dversion=$(cat .version) -Dpackaging=jar -DgeneratePom=true -DgeneratePom.description="Greenfoot."
  only:
    - tags
